### ISSUE TITLE
[doc] [low-prio] entry on wikipedia

### ISSUE THREAD

**Issue by mru00** [martine/ninja#1035]
Hi, 

https://en.wikipedia.org/wiki/List_of_build_automation_software does not list ninja. 

I added it: https://en.wikipedia.org/w/index.php?title=List_of_build_automation_software&diff=prev&oldid=685533289

**Comment by kirbyfan64** [comment]
There's a 99.99% chance they'll take that down because it's a red link and doesn't lead anywhere.

**Comment by martine** [comment]
It was added in the past, and removed in this change:
https://en.wikipedia.org/w/index.php?title=List_of_build_automation_software&oldid=569539703

**Comment by martine** [comment]
Oops I mean this change:
https://en.wikipedia.org/w/index.php?title=List_of_build_automation_software&direction=next&oldid=569539703

**Comment by nico** [comment]
If someone wanted to write a ninja page on Wikipedia, I think it has a slightly higher chance of surviving today given that it's the official build system of Chromium, the recommended by system of LLVM, Dolphin, and ReactOS (as far as I know), according to https://github.com/google/kati it can build Android, and it's been the subject of a published book.

I kind of want ninja-build.org the "official" homepage (i.e. make the current homepage forward to it instead of the other way round) and move the repo to an org-owned thing so that it looks more "real" to people who care about these things; that might help too.

In any case, thanks for adding it for a while :-)
