### ISSUE TITLE
Ninja invokes new jobs even after interruption

### ISSUE THREAD

**Issue by tzik** [martine/ninja#893]
Ninja invokes new jobs even after interruption.

On my environment, it runs around 1000-10000 jobs
before it terminates with "ninja: build stopped: interrupted by user. " message.

**Comment by martine** [comment]
How much time is 1000-10000 jobs?  Can you paste a log?  Which operating system?  How are you interrupting it?  What do the jobs do?  How loaded is your system when this happens?

**Comment by tzik** [comment]
I found ninja blocks SIGINT [here](https://github.com/martine/ninja/blob/master/src/subprocess-posix.cc#L155), is it intended?

> How much time is 1000-10000 jobs?
Every time I interrupt, it run extra 1000 for -j1000 ninja.

> Can you paste a log?
Let me mail it to you, since it's not open source yet.

> Which operating system?
Ubuntu Linux 14.04

> How are you interrupting it?
I typed Ctrl-C.

> What do the jobs do?
Each job compiles a C++.

> How loaded is your system when this happens?
loadavg was around 30, on my 32 core machine.

**Comment by sgraham** [comment]
On Thu, Jan 8, 2015 at 11:34 PM, Taiju Tsuiki <notifications@github.com>
wrote:

> I found ninja blocks SIGINT here
> <https://github.com/martine/ninja/blob/master/src/subprocess-posix.cc#L155>,
> is it intended?
>
> How much time is 1000-10000 jobs?
> Every time I interrupt, it run extra 1000 for -j1000 ninja.
>
>
Probably a silly question, but you're sure it's not just finishing the
existing 1000? Maybe a NINJA_STATUS with %s and %r could confirm that.

Can you paste a log?

**Comment by tzik** [comment]
I found that ppoll() doesn't deliver SIGINT if one of the fds has a event, even if a SIGINT is pending beforehand.

**Comment by nicolasdespres** [comment]
Taiju,

I already experienced ninja that did not catch SIGINT when it was executing
a long sequence of very short commands like "sleep 0" or "echo 0". I spent
quite a lot of time investigating the reason of this problem. Apparently,
Linux prioritises data over signal delivering.

See this thread for further information:
https://groups.google.com/forum/#!searchin/ninja-build/Does$20anybody$20has$20experienced$20ninja$20not$20interrupted$20when$20hitting$20control-c$3F/ninja-build/leEnr095PeA/abUdsJr_PawJ

A friend of mine suggested a better work around based on sigpending. I
wrote a small C program showing the problem. Tested on Linux 3.16.0-4-amd64.

==================================================
#include <stdio.h>
#include <signal.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <poll.h>

volatile int flag = 0;

void on_sigint(int signum) {
  flag = 1;
}

int main(int argc, char *argv[])
{
  sigset_t set;
  sigset_t old_mask;
  int nfds = 1;
  struct sigaction act, old_act;
  int ret;
  struct pollfd fds[1];
  sigset_t pending_set;

  printf("block SIGINT\n");
  sigemptyset(&set);
  sigaddset(&set, SIGINT);
  if (sigprocmask(SIG_BLOCK, &set, &old_mask) < 0)
  {
    perror("sigprocmask");
    return 1;
  }

  flag = 0;

  printf("setup sighandler [flag=%d]\n", flag);
  memset(&act, 0, sizeof(act));
  act.sa_handler = on_sigint;
  if (sigaction(SIGINT, &act, &old_act) < 0)
  {
    perror("sigaction");
    return 1;
  }

  printf("sleep while SIGINT is blocked [flag=%d]\n", flag);
  sleep(4);

  printf("call ppoll [flag=%d] (errno=%d [%s])\n", flag,
         errno, strerror(errno));
  fds[0].fd = STDIN_FILENO;
  fds[0].events = POLLIN | POLLPRI;
  fds[0].revents = 0;
  while (flag == 0)
  {
    ret = ppoll(fds, nfds, NULL, &old_mask);
    printf("ret=%d\n", ret);
    if (ret < 0)
      printf("error ppoll [flag=%d] (errno=%d [%s])\n",
             flag, errno, strerror(errno));
    else
      printf("end ppoll [flag=%d] (errno=%d [%s])\n",
             flag, errno, strerror(errno));
    sigemptyset(&pending_set);
    if (sigpending(&pending_set) < 0)
    {
      perror("sigpending");
      return 1;
    }
    if (sigismember(&pending_set, SIGINT)) {
      printf("SIGINT is pending!\n");
      flag = 1;
    }
    else
      printf("SIGINT is NOT pending!\n");
  }

  printf("end prog\n");
  return 0;
}
==================================================

If you try it without feeding any data on stdin:
$ ./ppoll-unblock
block SIGINT
setup sighandler [flag=0]
sleep while SIGINT is blocked [flag=0]
^Ccall ppoll [flag=0] (errno=0 [Success])
ret=-1
error ppoll [flag=1] (errno=4 [Interrupted system call])
SIGINT is NOT pending!
end prog

Control-C is hit when the message "sleep while SIGINT is blocked [flag=0]".
In this case the signal is delivered and ppoll exists with -1 and set
EINTR. So it is ok.

If you feed data to stdin:
$ cat /dev/zero | ./ppoll-unblock
block SIGINT
setup sighandler [flag=0]
sleep while SIGINT is blocked [flag=0]
^Ccall ppoll [flag=0] (errno=0 [Success])
ret=1
end ppoll [flag=0] (errno=0 [Success])
SIGINT is pending!
end prog

In this case the signal is not delivered by ppoll and the flag is set
thanks to the work around using sigpending not by ppoll.

IMO, this demonstrate the problem I experienced with Ninja because when it
has a lot of very short commands to execute, ppoll is kind of flooded with
data to process and does not deliver the signal. This is what I simulated
by feeding data to stdin in my example. I think if you add a similar work
around in Ninja this should fix your problem.

Hope it helps,
-Nico

On Fri, Jan 9, 2015 at 10:54 AM, Taiju Tsuiki <notifications@github.com>
wrote:

> I sent the log to both of you.
> I believe it's not just finishing existing jobs, since the number of
> running task (from %r) sticked to 1000 and started task (from %s) keeps
> increasing.
>
> I tried to add abort() to SubprocessSet::SetInterruptedFlag locally,
> though it doesn't hit.
> That implies Ninja didn't catch SIGINT.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/martine/ninja/issues/893#issuecomment-69313985>.
>



-- 
Nicolas Desprès

**Comment by tzik** [comment]
Hm, can we just stop masking the signal?

**Comment by tzik** [comment]
Make sense.

I locally tried to add sigpending check in SubprocessSet::DoWork.
That seems to enable SIGINT even in the flood of subprocess termination.

**Comment by nicolasdespres** [comment]
Glad it works.

On Sat, Jan 10, 2015 at 12:45 AM, Taiju Tsuiki <notifications@github.com>
wrote:

> Make sense.
>
> I locally tried to add sigpending check in SubprocessSet::DoWork.
> That seems to enable SIGINT even in the flood of subprocess termination.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/martine/ninja/issues/893#issuecomment-69421284>.
>



-- 
Nicolas Desprès

**Comment by nico** [comment]
Fixed by #897. Thanks for the patch!
