### ISSUE TITLE
Don't start commands with the same terminal as Ninja

### ISSUE THREAD

**Issue by jlnt** [martine/ninja#909]
On Linux at least, it looks like Ninja is starting commands in their own process group, but not in their own session.

The commands will run in the background but technically do have a terminal. Any access to the terminal will generate a SIGTTOU signal (which will stop the process). It's not a problem in general since commands are run without stdin/stdout/stderr pointing to the terminal (otherwise writing to stdout would SIGTTOU the process). However a process could open /dev/tty to access the terminal: instead of failing, this will succeed (as the process does indeed have a terminal) and it will be stopped if performing any ioctl.

This is causing some issues in Chromium/Mojo/Dart where "git svn" ends up calling the "resize" program which opens /dev/tty. The result is that "ninja" hangs because it transitively waits on a stopped process.

**Comment by jlnt** [comment]
Link to the Chromium bug: https://code.google.com/p/chromium/issues/detail?id=453175#c2

**Comment by nico** [comment]
ninja launches subprocesses via `execl("/bin/sh", "-c", command.str(), NULL)`.

Isn't opening /dev/tty kind of a silly thing to do? To me, this sounds a bit like "if a process has an endless loop, it will hang".

(If a program _wants_ a tty, it can use a console pool: http://martine.github.io/ninja/manual.html#_the_literal_console_literal_pool)

**Comment by jlnt** [comment]
Opening /dev/tty is the correct interface for a process to see if it is attached to a terminal. In turn, the returned file descriptor can be used to do things such as query the terminal size or resizing it. It's similar to how a process would write to stdout. There is nothing wrong about this.

Ninja is currently putting subprocesses in their own "background process group" (you may be more familiar with the shell terminology of "jobs"): https://github.com/martine/ninja/blob/62458b6f19dd134d2a4a38ff81e368c8b7e5605d/src/subprocess-posix.cc#L84

Creating a background process group and not detaching the terminal typically means: "I'm creating a process and if it interacts with the terminal, it'll be stopped until the user wants to interact with it". Shells like bash allow you to put "jobs" (process groups) in the "background" and the implicit contract is that if they write to the terminal they will be stopped, but the user will be able to put them back to the foreground at some point. Ninja is not honoring the contract and instead when such a process gets stopped, it just ignores it. Since it waits() for a stopped process, we end up with a form of deadlock.

This whole situation would normally not work at all: Ninja children would start writing to stdout and be immediately stopped. But since you replace stdout/stderr with a pipe, the worst use case is "hidden" and only the fringe case of using /dev/tty with ioctl() is problematic. In other words you're doing half of the job: you remove the file descriptors to read/write from/to the terminal, but you're not detaching the terminal.

I think the call to setpgid() should simply be replaced by setsid() which would create a new session, a new process group and make sure that this session has no controlling terminal. An alternative would be to  use TIOCNOTTY, but a new session should be what you want.

I'm happy to send a patch if you think you'd be amenable to accepting it after review.

**Comment by nico** [comment]
I thought the correct way was `isatty(0)`.

**Comment by nico** [comment]
Having said that, you know this better than I. I'm not opposed to thinking about changing this if you wrote a patch. I'm a bit scared about a change like this fixing some subtle bugs and causing others.

**Comment by jlnt** [comment]
I've created a pull request. I'm pretty confident in the patch (the risk / difficulty is in the unit test - but I think it's fine -). If we wanted to be super conservative, instead of creating a new session, we could detach the terminal. But I would rather do it "the right way" (with a new session).

**Comment by jlnt** [comment]
Friendly ping? It would be great to see this fixed. I tried to make the comments clear and hopefully this will convince you that it's the right thing to do.

The key is that changing file descriptor 0, 1 and 2 is not enough to detach from a terminal. It's a little bit of an oddity but it matters. The current version of the code already realized this and puts subprocesses in a new process group for this reason, but sessions are the right solution.

**Comment by nico** [comment]
(Looks generally fine, I just want to find time to do some testing with this.)

**Comment by nicolasdespres** [comment]
By putting child process in their own session (using setsid()) we can no longer forward them SIGTSTP because session leader ignore it. I do not know if it is really an issue because I have no use case of a program handling SIGTSTP and not running in the console pool.

If you try `sleep 60 | sleep 60 &` in bash and then use htop to send SIGTSTP to those two sleep process you will see them switching to state T (stopped). If you run `ninja -f misc/long-slow-build.ninja` the sleep processes started by ninja will just ignore SIGTSTP.

@jlnt I will try to use TIOCNOTTY as you suggested and see if it changes anything.

**Comment by nicolasdespres** [comment]
@jlnt Just check that replacing `setsid()` by `setpgid(0, 0)` allow subprocesses to receive SIGTSTP again.

I just pushed a patch that use `TIOCNOTTY` instead of `setsid()`: 79adb7144
That would be great it is still for your use case. In all case I will wait for the rational behind moving child processes to their own group before to send a PR.

**Comment by jlnt** [comment]
Sorry for the long delay. What do you mean by "receiving SIGSTP", what is sending SIGSTP, how and  to what?

Ctrl-Z for instance will still only SIGSTP the foreground process group, so your patch shouldn't change that. Could you elaborate a little about what is wrong? Maybe file a bug?

**Comment by nicolasdespres** [comment]
"receving SIGTSTP" = "the signal handler is called"
For the default handler it means turning the process state to suspended (T)

"sending SIGTSTP" = "kill -TSTP <pid>"

For my test I used htop because it let you easily select a bunch of processes and send a signal to all of them at once and see the change in the process state immediately. I selected the "sleep" processes and send SIGTSTP.

Without my patch the "sleep" processes ignore SIGTSTP whereas with my patch they do not since their state changes to "suspended" (I am assuming the default SIGTSTP handler is used by the "sleep" program).

You can install signal handler for SIGTSTP whereas you cannot for SIGSTOP. Some process may need it. I don't have any use case in mind specially for process running in the background (i.e. not requiring to be run in the "console" pool).

According to my research processes in their own session prevent them to receive SIGTSTP (I cannot find the web page where I read that, unfortunately).
