### ISSUE TITLE
ninja-syntax setup.py - Python3 has no execfile

### ISSUE THREAD

**Issue by NiklasRosenstein** [martine/ninja#980]
Hi! [ninja-syntax 1.5.3](https://pypi.python.org/pypi/ninja_syntax/1.5.3) uses `execfile()` in its setup script, but that built-in has been removed from Python 3. An easy fix would be to add the following after the imports:

```python
try:
    execfile
except NameError:
    # Python 3
    def execfile(filename, globals=None, locals=None):
        with open(filename) as fp:
            code = compile(fp.read(), filename, 'exec')
            exec(code, globals, locals)
```

Also, wouldn't it be better to have an extra repository for the ninja-syntax module? This way I could've made a pull request :)

**Comment by nico** [comment]
https://pypi.python.org/pypi/ninja_syntax/1.5.3 isn't from this repo, the home page entry on https://pypi.python.org/pypi/ninja_syntax/1.5.3 is wrong. I'd recommend bringing this up with that package's maintainer.

The ninja_syntax.py file is very simple and should work with Python 3 though, so maybe you can just copy it from https://github.com/martine/ninja/blob/master/misc/ninja_syntax.py instead of getting it through pypi.

**Comment by NiklasRosenstein** [comment]
Thanks for clarifying, Nico. It was listed in the Wiki and I thought it would be "official". I actually did copy the file into my project already, but I prefer to use an actual package if that was available.
