### ISSUE TITLE
Fatal: unknown deps type 'xyz' for a rule that does not have a 'deps' attribute

### ISSUE THREAD

**Issue by UberLambda** [martine/ninja#981]
You can see the [generated build.ninja files here](https://gist.github.com/UberLambda/3a8e196a288bc9b488f5)

Ninja emits the following error `ninja: fatal: unknown deps type 'glfw'`, after compiling `cpp/3rdparty/glfw/libglfw.a` (the file is in fact created, and it's the only target that gets attempted to be rebuilt every time i run ninja again)

Since the `static` rule does not specify any depfile (as you can see in `cpp/build.ninja`), are my scripts doing something else wrong, or have I not understood the error message? I can't pinpoint the exact problem here.

**Comment by martine** [comment]
Ah, funny!  The rules which don't specify a deps attribute inherit its value from the outer scope, which (due to this file: https://gist.github.com/UberLambda/3a8e196a288bc9b488f5#file-cpp_3rdparty_build-ninja-L5 ) is "glfw".

I am surprised this has never come up before.  I guess nobody ever has used "deps" as a variable name.  I guess the workaround is to not name that variable "deps".

**Comment by UberLambda** [comment]
Oh, I had no idea "deps" was a normal variable, I thought it was some kind of special attribute :O
Thanks for the help, I renamed the variable in the build script and it's working now!
